pubky.app_specs.md

Add pubky.app models specs

---

Cargo.lock
Cargo.toml
pubky.app_specs.md

Bump to v0.2.0

---

src/db/graph/queries/get.rs
src/db/kv/index/sets.rs
src/db/kv/traits.rs
src/models/follow/traits.rs
src/models/tag/stream.rs
src/models/tag/traits/collection.rs
src/models/user/muted.rs
src/models/user/stream.rs
src/routes/v0/stream/users.rs
tests/service/all.rs
tests/service/stream/mod.rs
tests/service/stream/users.rs

Feat(service): add stream of recommended users

---

src/db/graph/queries/get.rs

Fix(service): avoid self on recommended users

---

src/routes/v0/file/list.rs
src/routes/v0/notification/list.rs
src/routes/v0/post/tags.rs
src/routes/v0/stream/users.rs
src/routes/v0/tag/global.rs

This PR includes several updates and fixes to improve the clarity and consistency of API descriptions and handler logic. Changes are summarized below:
- Lowercased the reach type description for improved uniformity.
- Updated `user_id` references to `author_id` in the post tags handler for better clarity and semantic alignment.
- Refined the description for the `user stream by ID` endpoint to clarify its `POST` behavior.
- Updated tags and descriptions for user notifications endpoints to enhance documentation accuracy.
- Improved the description for the file list endpoint to clarify its `POST` behavior.
- Standardized terminology and descriptions across multiple files to ensure …

fix(docs): swagger docs

---

src/models/tag/global.rs
src/models/tag/search.rs
src/models/tag/stream.rs
src/routes/static.rs
src/types/timeframe.rs

Remove unsafe unwraps

---

src/models/post/stream.rs
src/models/user/tags.rs

chore: derive Default trait 

---

src/routes/v0/stream/posts.rs
tests/service/stream/post/tags.rs

fix: empty tags param bug on post stream endpoint

---

src/events/processor.rs

chore: improve poll events error handling

---

src/events/handlers/tag.rs

This fixes inconsistencies in the indexing process for some event synchronization cases

bug: inconsistent indexing

---

src/models/tag/global.rs
src/models/tag/mod.rs
src/models/tag/traits/taggers.rs
src/routes/v0/post/tags.rs
src/routes/v0/tag/global.rs
src/routes/v0/types.rs
src/routes/v0/user/tags.rs
tests/service/tags/post.rs
tests/service/tags/user.rs
tests/service/tags/wot.rs
tests/watcher/files/create.rs

chore: Improve Swagger Docs for tag/taggers Endpoint

---

nexus-api/src/routes/static/avatar.rs
nexus-api/src/routes/static/files.rs

As requested by @MiguelMedeiros , untested whether this has the expected benefit. The expiration is set to 1h.

Feat: add cache control header for files

---

Cargo.lock
nexus-api/Cargo.toml
nexus-common/Cargo.toml
nexus-common/src/models/file/details.rs
nexus-watcher/Cargo.toml
nexus-watcher/tests/files/create.rs
nexus-watcher/tests/posts/attachments.rs
nexus-watcher/tests/users/del_with_relations.rs

chore(deps): bump pubky-app-specs

---

Cargo.lock
nexus-api/Cargo.toml
nexus-common/Cargo.toml
nexus-watcher/Cargo.toml
nexus-watcher/examples/stress_network_sim.rs
nexus-watcher/tests/utils/watcher.rs

bump: pubky-core

---

Dockerfile

update DockerFile for nexusd

---

nexus-api/tests/stream/post/post_replies.rs
nexus-common/src/models/post/stream.rs
nexus-watcher/tests/posts/reply.rs

Same as #396 but strictly fixes the issue and add test cases for it without changing graph query.

fix(api): add skip to post replies

---

.github/workflows/test.yml

chore: workflow broken mirror

---

docker/test-graph/mocks/hot-tags.cypher
nexus-api/tests/stream/user/influencers.rs
nexus-api/tests/tags/hot.rs
nexus-common/src/db/graph/queries/get.rs

bug: fix active users cypher query

---

nexus-common/src/media/processors/image.rs

fix(common): auto orient vertical exif to webp

---

docker/test-graph/mocks/hot-tags.cypher
nexus-api/tests/tags/hot.rs
nexus-common/src/types/timeframe.rs

bug: fixed month timeframe for hot tags

---

Cargo.lock
nexus-api/Cargo.toml
nexus-common/Cargo.toml
nexusd/Cargo.toml

bump: missing crates

---

Cargo.lock
nexus-api/Cargo.toml
nexus-common/Cargo.toml
nexus-common/src/stack.rs
nexus-watcher/Cargo.toml

bump: otlp

---

nexus-api/Readme.md
nexus-api/src/lib.rs
nexus-common/Readme.md
nexus-common/src/lib.rs
nexus-watcher/Readme.md
nexus-watcher/src/lib.rs

chore(docs): add docstring and readme to crate modules

---

Cargo.lock
nexus-api/Cargo.toml
nexus-api/Readme.md
nexus-api/src/lib.rs
nexus-api/tests/stream/user/influencers.rs
nexus-api/tests/tags/hot.rs
nexus-common/Cargo.toml
nexus-common/Readme.md
nexus-common/src/db/graph/queries/get.rs
nexus-common/src/db/graph/setup.rs
nexus-common/src/db/kv/index/sorted_sets.rs
nexus-common/src/lib.rs
nexus-common/src/models/tag/stream.rs
nexus-common/src/models/tag/traits/collection.rs
nexus-common/src/models/traits.rs
nexus-common/src/models/user/influencers.rs
nexus-common/src/models/user/stream.rs
nexus-common/src/stack.rs
nexus-common/src/types/timeframe.rs
nexus-watcher/Cargo.toml
nexus-watcher/Readme.md
nexus-watcher/src/lib.rs
nexusd/Cargo.toml

chore: fix influencers query

---

nexus-api/src/routes/v0/endpoints.rs
nexus-api/src/routes/v0/stream/mod.rs
nexus-api/src/routes/v0/stream/posts.rs
nexus-api/src/routes/v0/stream/users.rs

feat: fetch posts in batch

---

Cargo.lock
nexus-api/Cargo.toml
nexus-api/src/builder.rs
nexus-watcher/src/builder.rs

feat: Services graceful shutdown

---

Cargo.lock
examples/README.md
nexus-api/src/builder.rs
nexus-common/Cargo.toml
nexus-common/src/db/connectors/neo4j.rs
nexus-common/src/db/connectors/redis.rs
nexus-common/src/db/graph/setup.rs
nexus-common/src/stack.rs
nexus-watcher/src/builder.rs
nexus-watcher/tests/utils/watcher.rs
nexusd/src/main.rs
nexusd/src/migrations/builder.rs

chore: control ddbb initialisation process

---

nexus-api/benches/setup.rs
nexus-common/default.config.toml
nexus-common/src/config/file/reader.rs
nexus-common/src/config/mod.rs

fix(common): surface default config

---

.dockerignore
Dockerfile

~- [ ] **Testing**: Implement and pass new tests for the new features/fixes, `cargo nextest run`.~
~- [ ] **Performance**: Ensure new code has relevant performance benchmarks, `cargo bench -p nexus-api`~

fix(docker): include 'examples' dir for successful build

---

Cargo.lock
nexus-api/Cargo.toml
nexus-common/Cargo.toml

chore: bump redis

---

Cargo.lock
nexus-common/Cargo.toml
nexus-watcher/Cargo.toml

chore: bump pubky

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
nexus-watcher/Cargo.toml
nexus-webapi/Cargo.toml

This PR bumps and consolidates `anyhow` dependency by defining it at workspace level.

Consolidate, bump `anyhow`

---

nexus-common/src/models/bootstrap.rs
nexus-webapi/tests/user/bootstrap.rs

feat: add in the bootstrap endpoint todays hot tags
