pubky/pubky-nexus

pubky.app_specs.md
These are 2 missing specs that we do not use in Nexus, but have become standard because the frontend writes and reads them as well:
- LastRead
- Custom Feeds
=> Add specs for feeds and least_read

src/models/pubky_app/post.rs, src/models/pubky_app/tag.rs, src/models/pubky_app/user.rs
Bug discovered by @catch-21 in https://github.com/pubky/pubky-app/issues/604
The watcher panics on sanitizing and validating strings with multibyte characters at the maximum length.
=> Fix(watcher): panics on multibyte characters cutoffs

examples/from_file.rs, src/events/mod.rs, src/events/processor.rs
New URIs are being added in the homeserver, but the watcher was incorrectly treating them as errors. This behavior has been updated to ignore these URIs since the app retrieves the content of those events directly from the homeserver. These are the newly introduced URIs:
- `pubky://{user_pubky}/pub/pubky.app/settings`
- `pubky://{user_pubky}/pub/pubky.app/last_read`
=> feat: Add more known URIs to watcher

.gitignore, src/db/graph/queries/put.rs, tests/watcher/users/del_with_relations.rs, tests/watcher/users/del_without_relations.rs
Fixes the put query for user using string "null" value instead of null.  
=> Fix user graph query handling of None values

src/models/post/stream.rs, tests/service/stream/post/mod.rs, tests/service/stream/post/post_replies.rs, tests/service/stream/post/reach/timeline.rs
In the post reach stream, the query to retrieve posts was missing `start` and end `filters`. As a result, it always returned the newest posts, making it impossible to retrieve older posts
🐛 reported by @MiguelMedeiros 
=> Bug: Reach post stream wrong

Cargo.lock, Cargo.toml, src/db/kv/traits.rs, src/lib.rs, src/models/file/details.rs, src/models/follow/followers.rs, src/models/follow/following.rs, src/models/follow/traits.rs, src/models/tag/post.rs, src/models/tag/stream.rs, src/models/tag/traits/collection.rs, src/models/tag/traits/taggers.rs, src/models/tag/user.rs, src/models/traits.rs, src/models/user/details.rs, src/models/user/follows.rs, src/models/user/muted.rs, src/routes/macros.rs, src/routes/v0/file/mod.rs, src/routes/v0/notification/mod.rs, src/routes/v0/post/mod.rs, src/routes/v0/search/mod.rs, src/routes/v0/tag/mod.rs, src/routes/v0/user/mod.rs
Latest `pubky-core` conflicts in version of `bytes` with axum 0.7.9 . This can be fixed by upgrading to axum 0.8.0 which required: 
1. Bumping utoipa to latest commit in main.
2. Do the same in `pubky-app-specs` repo.
2. Changing how params in endpoints are prefixed. Axum 0.8 changes `:param` to `{param}` so our macro for swagger/axum is not needed anymore.
=> chore(deps): bump axum to 0.8.1

docker/db-graph/mocks/hot-tags.cypher, tests/service/tags/hot.rs
=> fix hot tags tests failing based on time of the month

Dockerfile
Still defaults to x86. Pass build arg when using ARM architecture: `docker build --build-arg TARGETARCH=aarch64 .`
- ~[ ] **Testing**: Implement and pass new tests for the new features/fixes, `cargo test`.~
- ~[ ] **Performance**: Ensure new code has relevant performance benchmarks, `cargo bench`~
=> fix: ARM (Apple Silicon) build support in Dockerfile

Cargo.lock, Cargo.toml
Some code was merged and released, now we can stop using the custom git rev pin.
=> chore(deps): use utoipa from crates again

src/db/migrations/manager.rs, src/db/migrations/migrations_list/mod.rs, src/db/migrations/migrations_list/tag_counts_reset_1739459180.rs, src/db/migrations/mod.rs
This is a migration that ensures outdated indexes are deleted before re-indexing fresh counts from the graph. The update prevents obsolete data from persisting in Redis and ensures consistency between the graph database and indexed counts
=> chore: user and post counts migration

Cargo.lock, Cargo.toml, src/setup.rs
more info about the structs renaming [here](https://github.com/open-telemetry/opentelemetry-rust/blob/main/docs/migration_0.28.md#rename-sdk-structs)
=> deps: opentelemetry

Cargo.lock, nexus-api/Cargo.toml, nexus-api/src/routes/mod.rs, nexus-api/tests/stream/post/posts.rs, nexus-api/tests/stream/user/influencers.rs, nexus-api/tests/stream/user/list.rs, nexus-api/tests/stream/user/score.rs, nexus-api/tests/tags/post.rs, nexus-api/tests/tags/search.rs, nexus-api/tests/tags/user.rs, nexus-api/tests/tags/wot.rs, nexus-api/tests/user/reach.rs, nexus-api/tests/user/search.rs, nexus-api/tests/user/views.rs, nexus-api/tests/utils/mod.rs
- Integrates CompressionLayer from tower‑http into the Axum stack
- Automatically compresses all responses to reduce payload size and improve performance
- Remove dev dependency `reqwest` that was not really needed as we can use `axum` types.
Request responses now transfer anywhere between 60%-90% more data. A `/stream/post` with 30 members transfer only `1.7Kb` vs `15.9Kb` before this PR on a modern browser using `zstd` . It also support `gzip`, `brotli` and `deflate` depending on browser's support.
=> feat(api): add response compression with tower‑http

nexus-api/benches/streams_benches/author.rs, nexus-api/benches/streams_benches/bookmarks.rs, nexus-api/benches/streams_benches/kind.rs, nexus-api/benches/streams_benches/reach.rs, nexus-api/benches/streams_benches/sorting.rs, nexus-api/benches/streams_benches/tag.rs, nexus-api/src/routes/v0/stream/posts.rs, nexus-api/tests/stream/post/post_replies.rs, nexus-common/src/db/kv/index/sorted_sets.rs, nexus-common/src/models/post/stream.rs, nexus-watcher/tests/bookmarks/del.rs, nexus-watcher/tests/bookmarks/raw.rs, nexus-watcher/tests/bookmarks/viewer.rs, nexus-watcher/tests/posts/reply.rs
Sorting post replies in ascending order helps in a great way to fix https://github.com/pubky/pubky-app/issues/1241
as @flaviomoceri requested, `order=ascending|descending` can not be requested by the client.
=> fix(models): allow stream of post in ascending order

nexus-common/src/db/kv/index/sets.rs, nexus-common/src/models/post/stream.rs
Previously, we were extracting 5 users in the applied reach
=> bug: add a custom limit for user reach in post streams

nexus-common/src/types/timeframe.rs
=> fix: running timeframe hot tags

nexus-api/tests/tags/hot.rs, nexus-common/src/db/graph/queries/get.rs, nexus-common/src/db/graph/setup.rs, nexus-common/src/db/kv/index/sorted_sets.rs, nexus-common/src/models/tag/stream.rs, nexus-common/src/models/tag/traits/collection.rs, nexus-common/src/models/traits.rs, nexus-common/src/models/user/influencers.rs, nexus-common/src/models/user/stream.rs, nexus-common/src/types/timeframe.rs
* delete OPTIONAL MATCH in influencer cypher
* bump crates (#410)
* bump otlp (#409)
* chore(docs): add docstring and readme to crate modules (#382)
* deps: bump clap from 4.5.32 to 4.5.34 (#405)
Bumps [clap](https://github.com/clap-rs/clap) from 4.5.32 to 4.5.34.
- [Release notes](https://github.com/clap-rs/clap/releases)
- [Changelog](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md)
- [Commits](https://github.com/clap-rs/clap/compare/clap_complete-v4.5.32...clap_complete-v4.5.34)
---
updated-dependencies:
- dependency-name: clap dependency-version: 4.5.34 dependency-type: direct:production update-type: version-update:semver-patch ...
* fix query: missing timeframe. Add new index, tag.indexed_at
* taggers vector order changed
* clippy lint
* even user_id is added in influencer …
=> chore: fix influencers query (#411)

Cargo.lock, nexus-common/Cargo.toml, nexus-common/src/db/connectors/redis.rs
Same as #420 but using `deadpool-redis` instead for hopefully better scalability.
=> fix(common): redis with deadpool

docker/test-graph/mocks/posts.cypher, nexus-common/src/db/graph/queries/get.rs
=> bug: stream query includes post replies

README.md, nexus-api/src/builder.rs, nexus-watcher/src/builder.rs, nexusd/src/cli.rs, nexusd/src/launcher.rs, nexusd/src/main.rs
=> chore: rename cli config parameter in nexusd service

nexus-api/build.rs
Before this PR, running any command that involved `nexus-api` code, like
```sh
cargo run -p nexusd -- db clear
```
resulted every time in ~7s of recompilation, even when no code was changed.
This is happening because the `build.rs` lines
```rust
println!("cargo:rerun-if-changed=.git/HEAD");
println!("cargo:rerun-if-changed=.git/refs/heads");
```
referenced files and folders in the workspace root's `.git` directory, from within a workspace member.
The path was incorrect, which led `cargo` to believe these files changed (cause they are missing => they were likely removed), which caused re-compilation on every run.
This PR fixes the paths, which removes unnecessary re-compilations when running commands locally.
=> Speed up local responsiveness by removing unnecessary recompilations

docker/docker-compose.yml
At the moment, nexus is using neo4j 5.24.2 community edition:
https://hub.docker.com/layers/library/neo4j/5.24.2-community/images/sha256-ffff134844a864de02be2f07eeb0e81ebd8c97b0a26f4cde981f5d4745bd559c
which has quite a bit of known vulnerabilities, compared to the latest 5.26.7:
https://hub.docker.com/layers/library/neo4j/5.26.7-community/images/sha256-a808dea9a2910966bfa6369fdb9293a34ac08217c14957c611f541b63e9ba925
5.26 is a LTS (long-term support) release and will receive hot fixes until June 2028:
https://neo4j.com/developer/kb/neo4j-supported-versions/
Therefore, this PR bumps neo4j to the latest 5.26 version.
=> Bump neo4j to v5.26.7

.gitignore
This is a cosmetic PR that improves dev experience.
Each time mock data is added and the tests are run, this generates quite a few static files in `nexus-api` and `nexus-watcher`. The git client shows them as untracked files, which clutters the UI and risks accidentally including them in a commit.
So this PR adds these static files to `.gitignore`.
=> Add nexus static files to `.gitignore`

nexus-common/src/models/post/counts.rs, nexus-common/src/models/user/counts.rs, nexus-watcher/tests/tags/post_put.rs
This PR fixes an issue with the `unique_tags` counter in Redis indexes for both posts and users.
The problem can be reproduced as follows for users:
* create a new user with no new tags on its profile
* self-tag
* check the user counts at `/v0/user/{user_id}/counts`
* they will include `tags: 1, unique_tags: 1`
* remove the user tag
* check the user counts at `/v0/user/{user_id}/counts`
* they will include `tags: 0, unique_tags: 0`
* re-add the tag again
* check the user counts at `/v0/user/{user_id}/counts`
* they will include `tags: 1, unique_tags: 0`
* from this point on, this discrepancy between `tags` and `unique_tags` will remain
In a similar way, it can be also reproduced for posts:
* create a new post with no new tags
* tag the post
* check the post tag counts at …
=> Fix unreliable `unique_tags` counter

nexus-api/benches/bootstrap.rs, nexus-api/benches/follows.rs, nexus-api/benches/post.rs, nexus-api/benches/search.rs, nexus-api/benches/streams_benches/author.rs, nexus-api/benches/streams_benches/bookmarks.rs, nexus-api/benches/streams_benches/kind.rs, nexus-api/benches/streams_benches/reach.rs, nexus-api/benches/streams_benches/sorting.rs, nexus-api/benches/streams_benches/tag.rs, nexus-api/benches/streams_benches/user.rs, nexus-api/benches/tag.rs, nexus-api/benches/user.rs, nexus-watcher/tests/posts/del_with_attachments.rs, nexus-watcher/tests/posts/mod.rs
- Fixes deprecation warning for the criterion crate: WARNING - _use of deprecated function `criterion::black_box`: use `std::hint::black_box()`_
- Adds a new integration test for the `DEL` action on posts with attachments
=> test: DEL post attachments

nexus-common/src/models/mod.rs, nexus-common/src/models/tag/search.rs, nexus-common/src/models/user/search.rs, nexus-watcher/src/events/handlers/tag.rs, nexus-webapi/src/routes/v0/endpoints.rs, nexus-webapi/src/routes/v0/search/mod.rs, nexus-webapi/src/routes/v0/search/users.rs, nexus-webapi/tests/user/search.rs
This PR adds a new endpoint `/search/users//by_id/{prefix}` that returns a list of User IDs based on the given ID prefix.
Fixes #446
=> Add autocomplete endpoint: user search by PK prefix

Cargo.lock, Cargo.toml, nexus-common/Cargo.toml, nexus-webapi/Cargo.toml
This PR bumps `redis` and `redis-deadpool` dependencies.
Supersedes #501
=> Bump `deadpool-redis` deps

Cargo.lock, Cargo.toml, examples/Cargo.toml
This PR bumps `tokio` at workspace level and updates `examples/Cargo.toml` to re-use it.
=> Consolidate and bump `tokio` dependency

nexus-watcher/src/events/processor.rs, nexus-watcher/src/events/processor_factory.rs, nexus-watcher/src/events/traits/tevent_processor.rs, nexus-watcher/src/events/traits/tevent_processor_factory.rs, nexus-watcher/tests/service/event_processing_multiple_homeservers.rs, nexus-watcher/tests/service/mock_event_processor.rs, nexus-watcher/tests/service/signal.rs, nexus-watcher/tests/service/utils/mod.rs, nexus-watcher/tests/service/utils/processor.rs, nexus-watcher/tests/service/utils/processor_factory.rs
This PR uses `Arc` instead of `Box`, which simplifies the ownership management for the event processors.
It also removes the need for `&mut self` in some of the methods.
Due to how `shutdown_rx` is used, this change also brings:
- removing `shutdown_rx` from the `MockEventProcessorFactory`, because it's not used by the factory itself
- it is used by the real factory when building the event processors, but the mock one takes pre-built processors on initialization
- `create_random_homeservers_and_persist` now asks for `shutdown_rx` as arg instead of creating a new random one, which forces the caller to use the same `shutdown_rx` across all mock event processors, which emulates the behavior of the real event processor
=> Change from `Box<dyn TEventProcessor>` to `Arc`

nexus-common/src/models/homeserver.rs
The previous implementation only threw an error if the `Option<Vec<String>>` as a `None`.
The PR extends the logic and also covers the case when it is `Some`, but the list is empty.
=> Fix `Homeserver::get_all_from_graph()`: throw error on empty list

nexus-watcher/src/service/processor_factory.rs, nexus-watcher/src/service/traits/tevent_processor_factory.rs, nexus-watcher/tests/service/event_processor_prioritization.rs, nexus-watcher/tests/service/utils/processor_factory.rs
This PR renames `prioritize_default_homeserver()` to `homeservers_by_priority()`, as it implies a more general ordering in addition to placing the default one first.
=> Rename `prioritize_default_homeserver()` -> `homeservers_by_priority()`

nexus-watcher/src/service/constants.rs, nexus-watcher/src/service/processor.rs, nexus-watcher/src/service/processor_factory.rs, nexus-watcher/src/service/traits/tevent_processor.rs, nexus-watcher/src/service/traits/tevent_processor_factory.rs, nexus-watcher/tests/event_processor/network/counts.rs, nexus-watcher/tests/event_processor/tags/fail_index.rs, nexus-watcher/tests/service/event_processing_multiple_homeservers.rs, nexus-watcher/tests/service/event_processor_prioritization.rs, nexus-watcher/tests/service/mock_event_processor.rs, nexus-watcher/tests/service/signal.rs, nexus-watcher/tests/service/utils/processor.rs, nexus-watcher/tests/service/utils/processor_factory.rs
This PR makes sure that any individual processor run which panics will not stop the wrapper `run_all`. This allows the indexer to continue indexing undisturbed.
To achieve this,`TEventProcessor` was changed as follows:
- `run` has a trait default implementation which internally calls `run_internal` and checks for timeout, panic or errors
- `run_internal` is the raw event processor run. For `EventProcessor`, it deals with fetching and processing events. For `MockEventProcessor`, it simulates a certain run behavior. Note that both the mock and the real implementation are subject to the same timeout and panic checks in `run`.
- got various utilities, like `timeout()` (moved from the factory) and `get_homeserver_id()`
=> Correctly handle and track panicks in event processor runs

nexus-watcher/src/service/processor_factory.rs, nexus-watcher/src/service/traits/tevent_processor_factory.rs
This PR updates a few comments:
- removes duplicate comment on a `TEventProcessFactory::homeservers_by_priority` implementation, as the trait method rustdoc already describes it
- rewrites the trait `build` and `run_all` rustdocs to reflect the latest signature changes
=> Update a few `TEventProcessFactory` comments
